set_alarm:
  name: Set Alarm
  description: Set an alarm with specified parameters.
  fields:
    satellite:
      name: Satellite
      description: The satellite to announce the alarm on (mutually exclusive with media_player)
      example: "default_satellite"
      selector:
        select:
          options:
            - "default_satellite"
            - "kitchen"
            - "bedroom"
            - "living_room"
    media_player:
      name: Media Player
      description: Media player to play alarm on (mutually exclusive with satellite)
      selector:
        entity:
          domain: media_player
    time:
      name: Time
      description: The time for the alarm
      selector:
        time: {}
    date:
      name: Date
      description: Optional date for the alarm (defaults to today)
      selector:
        date: {}
    message:
      name: Message
      description: Optional message to announce
      example: "Time to wake up!"
      selector:
        text: {}
    repeat:
      name: Repeat
      description: How to repeat the alarm
      default: "once"
      selector:
        select:
          options:
            - "once"
            - "daily"
            - "weekdays"
            - "weekends"
            - "weekly"
            - "custom"
    repeat_days:
      name: Custom Repeat Days
      description: Days to repeat on if repeat mode is custom
      selector:
        select:
          multiple: true
          options:
            - "mon"
            - "tue"
            - "wed"
            - "thu"
            - "fri"
            - "sat"
            - "sun"

set_reminder:
  name: Set Reminder
  description: Set a reminder with specified parameters.
  fields:
    satellite:
      name: Satellite
      description: The satellite to announce the reminder on (mutually exclusive with media_player)
      example: "default_satellite"
      selector:
        select:
          options:
            - "default_satellite"
            - "kitchen"
            - "bedroom"
            - "living_room"
    media_player:
      name: Media Player
      description: Media player to play reminder on (mutually exclusive with satellite)
      selector:
        entity:
          domain: media_player
    time:
      name: Time
      description: The time for the reminder
      selector:
        time: {}
    date:
      name: Date
      description: Optional date for the reminder (defaults to today)
      selector:
        date: {}
    message:
      name: Message
      description: Optional message to announce
      example: "Take medication"
      selector:
        text: {}
    repeat:
      name: Repeat
      description: How to repeat the reminder
      default: "once"
      selector:
        select:
          options:
            - "once"
            - "daily"
            - "weekdays"
            - "weekends"
            - "weekly"
            - "custom"
    repeat_days:
      name: Custom Repeat Days
      description: Days to repeat on if repeat mode is custom
      selector:
        select:
          multiple: true
          options:
            - "mon"
            - "tue"
            - "wed"
            - "thu"
            - "fri"
            - "sat"
            - "sun"

stop_alarm:
  description: Stop an active alarm or reminder
  fields:
    alarm_id:
      description: ID of the alarm/reminder to stop
      example: "alarm_123"

snooze_alarm:
  description: Snooze an active alarm or reminder
  fields:
    alarm_id:
      description: ID of the alarm/reminder to snooze
      example: "alarm_123"
    minutes:
      description: Number of minutes to snooze
      example: 5
      default: 5

stop_reminder:
  description: Stop an active reminder
  fields:
    reminder_id:
      description: ID of the reminder to stop
      example: "reminder_123"

snooze_reminder:
  description: Snooze an active reminder
  fields:
    reminder_id:
      description: ID of the reminder to snooze
      example: "reminder_123"
    minutes:
      description: Number of minutes to snooze
      example: 5
      default: 5