set_alarm:
  name: Set Alarm
  description: Set an alarm with specified parameters.
  fields:
    time:
      name: Time
      description: The time for the alarm (required)
      required: true
      selector:
        time: {}
    name:
      name: Name
      description: Optional name for the alarm (can include spaces)
      example: "Morning Wake Up"
      required: false
      selector:
        text:
          multiline: false
    date:
      name: Date
      description: Optional date for the alarm (defaults to today)
      required: false
      selector:
        date: {}
    satellite:
      name: Satellite
      description: The satellite to announce the alarm on (mutually exclusive with media_player)
      selector:
        entity:
          domain: assist_satellite
    media_player:
      name: Media Player
      description: Media player to play alarm on (mutually exclusive with satellite)
      selector:
        entity:
          domain: media_player
    message:
      name: Message
      description: Optional message to announce
      example: "Time to wake up!"
      selector:
        text:
          multiline: false
    repeat:
      name: Repeat
      description: How to repeat the alarm
      default: "once"
      selector:
        select:
          options:
            - "once"
            - "daily"
            - "weekdays"
            - "weekends"
            - "weekly"
            - "custom"
    repeat_days:
      name: Custom Repeat Days
      description: Days to repeat on if repeat mode is custom
      selector:
        select:
          multiple: true
          options:
            - "mon"
            - "tue"
            - "wed"
            - "thu"
            - "fri"
            - "sat"
            - "sun"
    sound_file:
      name: Sound File
      description: Path to custom sound file (default is birds.mp3)
      required: false
      example: "/custom_components/alarms_and_reminders/sounds/alarms/birds.mp3"
      selector:
        text:
          multiline: false
    notify_device:
      name: Notify Device
      description: Mobile app device to notify (e.g., mobile_app_phone)
      required: false
      example: "mobile_app_pixel_6"
      selector:
        select:
          options:
            - "notify.mobile_app"  # Default mobile notify service
          custom_value: true       # Allow custom input
          multiple: true          # Allow multiple devices

set_reminder:
  name: Set Reminder
  description: Set a reminder with specified parameters.
  fields:
    time:
      name: Time
      description: The time for the reminder (required)
      required: true
      selector:
        time: {}
    name:
      name: Name
      description: Name for the reminder (required, can include spaces)
      example: "Take Medication"
      required: true
      selector:
        text:
          multiline: false
    date:
      name: Date
      description: Optional date for the reminder (defaults to today)
      required: false
      selector:
        date: {}
    satellite:
      name: Satellite
      description: The satellite to announce the reminder on (mutually exclusive with media_player)
      example: "default_satellite"
      selector:
        entity:
          domain: assist_satellite
    media_player:
      name: Media Player
      description: Media player to play reminder on (mutually exclusive with satellite)
      selector:
        entity:
          domain: media_player
    message:
      name: Message
      description: Optional message to announce
      example: "Take medication"
      selector:
        text: {}
    repeat:
      name: Repeat
      description: How to repeat the reminder
      default: "once"
      selector:
        select:
          options:
            - "once"
            - "daily"
            - "weekdays"
            - "weekends"
            - "weekly"
            - "custom"
    repeat_days:
      name: Custom Repeat Days
      description: Days to repeat on if repeat mode is custom
      selector:
        select:
          multiple: true
          options:
            - "mon"
            - "tue"
            - "wed"
            - "thu"
            - "fri"
            - "sat"
            - "sun"
    sound_file:
      name: Sound File
      description: Path to custom sound file (default is ringtone.mp3)
      required: false
      example: "/custom_components/alarms_and_reminders/sounds/reminders/ringtone.mp3"
      selector:
        text:
          multiline: false
    notify_device:
      name: Notify Device
      description: Mobile app device to notify (e.g., mobile_app_phone)
      required: false
      example: "mobile_app_pixel_6"
      selector:
        select:
          options:
            - "notify.mobile_app"  # Default mobile notify service
          custom_value: true       # Allow custom input
          multiple: true          # Allow multiple devices

stop_alarm:
  name: Stop Alarm
  description: Stop an active alarm
  fields:
    alarm_id:
      name: Alarm
      description: Select the alarm to stop
      required: true
      selector:
        entity:
          domain: alarms_and_reminders
          filter:
            state: 
              - "active"
              - "scheduled"
            attributes:
              is_alarm: true

snooze_alarm:
  name: Snooze Alarm
  description: Snooze a ringing alarm
  fields:
    minutes:
      name: Minutes
      description: Number of minutes to snooze
      default: 5
      required: false
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: minutes
    alarm_id:
      name: Alarm
      description: The alarm to snooze
      required: true
      selector:
        entity:
          domain: alarms_and_reminders
          integration: alarms_and_reminders
          filter:
            state: active
            attributes:
              is_alarm: true

stop_reminder:
  name: Stop Reminder
  description: Stop an active reminder
  fields:
    reminder_id:
      name: Reminder
      description: Select the reminder to stop
      required: true
      selector:
        entity:
          domain: alarms_and_reminders
          filter:
            state: 
              - "active"
              - "scheduled"
            attributes:
              is_alarm: false

snooze_reminder:
  name: Snooze Reminder
  description: Snooze a ringing reminder
  fields:
    minutes:
      name: Minutes
      description: Number of minutes to snooze
      default: 5
      required: false
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: minutes
    reminder_id:
      name: Reminder
      description: The reminder to snooze
      required: true
      selector:
        entity:
          domain: alarms_and_reminders
          integration: alarms_and_reminders
          filter:
            state: active
            attributes:
              is_alarm: false

stop:
  name: Stop
  description: Stop an active alarm or reminder
  target:
    entity:
      domain: alarms_and_reminders

snooze:
  name: Snooze
  description: Snooze an active alarm or reminder
  target:
    entity:
      domain: alarms_and_reminders
  fields:
    minutes:
      name: Minutes
      description: Number of minutes to snooze
      default: 5
      selector:
        number:
          min: 1
          max: 60
          step: 1

delete:
  name: Delete
  description: Delete an alarm or reminder
  target:
    entity:
      domain: alarms_and_reminders

stop_all_alarms:
  name: Stop All Alarms
  description: Stop all active alarms
  fields: {}

stop_all_reminders:
  name: Stop All Reminders
  description: Stop all active reminders
  fields: {}

stop_all:
  name: Stop All
  description: Stop all active alarms and reminders
  fields: {}

edit_alarm:
  name: Edit Alarm
  description: Edit an existing alarm's settings
  fields:
    alarm_id:
      name: Alarm
      description: Select the alarm to edit
      required: true
      selector:
        entity:
          domain: alarms_and_reminders
          filter:
            attributes:
              is_alarm: true
    time:
      name: Time
      description: New time for the alarm (HH:MM format)
      required: false
      example: "07:30"
      selector:
        time: {}
    date:
      name: Date
      description: New date for the alarm
      required: false
      selector:
        date: {}
    name:
      name: Name
      description: New name for the alarm
      required: false
      selector:
        text: {}
    message:
      name: Message
      description: New message for the alarm
      required: false
      selector:
        text: {}
    satellite:
      name: Satellite
      description: New satellite for the alarm
      required: false
      selector:
        entity:
          domain: assist_satellite
    media_player:
      name: Media Player
      description: New media player for the alarm
      required: false
      selector:
        entity:
          domain: media_player

edit_reminder:
  name: Edit Reminder
  description: Edit an existing reminder's settings
  fields:
    reminder_id:
      name: Reminder
      description: Select the reminder to edit
      required: true
      selector:
        entity:
          domain: alarms_and_reminders
          filter:
            attributes:
              is_alarm: false
    time:
      name: Time
      description: New time for the reminder (HH:MM format)
      required: false
      example: "07:30"
      selector:
        time: {}
    date:
      name: Date
      description: New date for the reminder
      required: false
      selector:
        date: {}
    name:
      name: Name
      description: New name for the reminder
      required: false
      selector:
        text: {}
    message:
      name: Message
      description: New message for the reminder
      required: false
      selector:
        text: {}
    satellite:
      name: Satellite
      description: New satellite for the reminder
      required: false
      selector:
        entity:
          domain: assist_satellite
    media_player:
      name: Media Player
      description: New media player for the reminder
      required: false
      selector:
        entity:
          domain: media_player

delete_alarm:
  name: Delete Alarm
  description: Delete a specific alarm
  fields:
    alarm_id:
      name: Alarm ID
      description: The ID of the alarm to delete
      required: true
      selector:
        entity:
          domain: alarms_and_reminders
          filter:
            attributes:
              is_alarm: true

delete_reminder:
  name: Delete Reminder
  description: Delete a specific reminder
  fields:
    reminder_id:
      name: Reminder ID
      description: The ID of the reminder to delete
      required: true
      selector:
        entity:
          domain: alarms_and_reminders
          filter:
            attributes:
              is_alarm: false

delete_all_alarms:
  name: Delete All Alarms
  description: Delete all alarms
  fields: {}

delete_all_reminders:
  name: Delete All Reminders
  description: Delete all reminders
  fields: {}

delete_all:
  name: Delete All
  description: Delete all alarms and reminders
  fields: {}

reschedule_alarm:
  name: Reschedule Alarm
  description: Reschedule a stopped or completed alarm
  fields:
    alarm_id:
      name: Alarm
      description: The alarm to reschedule
      required: true
      selector:
        entity:
          domain: alarms_and_reminders
          filter:
            attributes:
              is_alarm: true
    time:
      name: Time
      description: New time for the alarm (optional)
      required: false
      selector:
        time: {}
    date:
      name: Date
      description: New date for the alarm (optional)
      required: false
      selector:
        date: {}
    message:
      name: Message
      description: New message (optional)
      required: false
      selector:
        text: {}
    satellite:
      name: Satellite
      description: New satellite (optional)
      required: false
      selector:
        entity:
          domain: assist_satellite
    media_player:
      name: Media Player
      description: New media player (optional)
      required: false
      selector:
        entity:
          domain: media_player

reschedule_reminder:
  name: Reschedule Reminder
  description: Reschedule a stopped or completed reminder
  fields:
    reminder_id:
      name: Reminder
      description: The reminder to reschedule
      required: true
      selector:
        entity:
          domain: alarms_and_reminders
          filter:
            attributes:
              is_alarm: false
    time:
      name: Time
      description: New time for the reminder (optional)
      required: false
      selector:
        time: {}
    date:
      name: Date
      description: New date for the reminder (optional)
      required: false
      selector:
        date: {}
    message:
      name: Message
      description: New message (optional)
      required: false
      selector:
        text: {}
    satellite:
      name: Satellite
      description: New satellite (optional)
      required: false
      selector:
        entity:
          domain: assist_satellite
    media_player:
      name: Media Player
      description: New media player (optional)
      required: false
      selector:
        entity:
          domain: media_player
