set_alarm:
  name: Set Alarm
  description: Set an alarm with specified parameters.
  fields:
    time:
      name: Time
      description: The time for the alarm (required)
      required: true
      selector:
        time: {}
    name:
      name: Name
      description: Optional name for the alarm (can include spaces)
      example: "Morning Wake Up"
      required: false
      selector:
        text:
          multiline: false
    date:
      name: Date
      description: Optional date for the alarm (defaults to today)
      required: false
      selector:
        date: {}
    satellite:
      name: Satellite
      description: The satellite to announce the alarm on (mutually exclusive with media_player)
      selector:
        entity:
          domain: assist_satellite
    media_player:
      name: Media Player
      description: Media player to play alarm on (mutually exclusive with satellite)
      selector:
        entity:
          domain: media_player
    message:
      name: Message
      description: Optional message to announce
      example: "Time to wake up!"
      selector:
        text:
          multiline: false
    repeat:
      name: Repeat
      description: How to repeat the alarm
      default: "once"
      selector:
        select:
          options:
            - "once"
            - "daily"
            - "weekdays"
            - "weekends"
            - "weekly"
            - "custom"
    repeat_days:
      name: Custom Repeat Days
      description: Days to repeat on if repeat mode is custom
      selector:
        select:
          multiple: true
          options:
            - "mon"
            - "tue"
            - "wed"
            - "thu"
            - "fri"
            - "sat"
            - "sun"

set_reminder:
  name: Set Reminder
  description: Set a reminder with specified parameters.
  fields:
    time:
      name: Time
      description: The time for the reminder (required)
      required: true
      selector:
        time: {}
    name:
      name: Name
      description: Name for the reminder (required, can include spaces)
      example: "Take Medication"
      required: true
      selector:
        text:
          multiline: false
    date:
      name: Date
      description: Optional date for the reminder (defaults to today)
      required: false
      selector:
        date: {}
    satellite:
      name: Satellite
      description: The satellite to announce the reminder on (mutually exclusive with media_player)
      example: "default_satellite"
      selector:
        entity:
          domain: assist_satellite
    media_player:
      name: Media Player
      description: Media player to play reminder on (mutually exclusive with satellite)
      selector:
        entity:
          domain: media_player
    message:
      name: Message
      description: Optional message to announce
      example: "Take medication"
      selector:
        text: {}
    repeat:
      name: Repeat
      description: How to repeat the reminder
      default: "once"
      selector:
        select:
          options:
            - "once"
            - "daily"
            - "weekdays"
            - "weekends"
            - "weekly"
            - "custom"
    repeat_days:
      name: Custom Repeat Days
      description: Days to repeat on if repeat mode is custom
      selector:
        select:
          multiple: true
          options:
            - "mon"
            - "tue"
            - "wed"
            - "thu"
            - "fri"
            - "sat"
            - "sun"

stop_alarm:
  name: Stop Alarm
  description: Stop an active alarm
  fields:
    alarm_id:
      name: Alarm
      description: Select the alarm to stop
      required: true
      selector:
        entity:
          domain: alarms_and_reminders
          filter:
            state: 
              - "active"
              - "scheduled"
            attributes:
              is_alarm: true

snooze_alarm:
  name: Snooze Alarm
  description: Snooze an active alarm
  fields:
    alarm_id:
      name: Alarm ID
      description: ID of the alarm to snooze
      required: true
      example: "alarm_1"
      selector:
        text:
    minutes:
      name: Minutes
      description: Number of minutes to snooze
      default: 5
      selector:
        number:
          min: 1
          max: 60
          step: 1

stop_reminder:
  name: Stop Reminder
  description: Stop an active reminder
  fields:
    reminder_id:
      name: Reminder
      description: Select the reminder to stop
      required: true
      selector:
        entity:
          domain: alarms_and_reminders
          filter:
            state: 
              - "active"
              - "scheduled"
            attributes:
              is_alarm: false

snooze_reminder:
  description: Snooze an active reminder
  fields:
    reminder_id:
      description: ID of the reminder to snooze
      example: "reminder_123"
    minutes:
      description: Number of minutes to snooze
      example: 5
      default: 5

stop:
  name: Stop
  description: Stop an active alarm or reminder
  target:
    entity:
      domain: alarms_and_reminders

snooze:
  name: Snooze
  description: Snooze an active alarm or reminder
  target:
    entity:
      domain: alarms_and_reminders
  fields:
    minutes:
      name: Minutes
      description: Number of minutes to snooze
      default: 5
      selector:
        number:
          min: 1
          max: 60
          step: 1

delete:
  name: Delete
  description: Delete an alarm or reminder
  target:
    entity:
      domain: alarms_and_reminders

stop_all_alarms:
  name: Stop All Alarms
  description: Stop all active alarms
  fields: {}

stop_all_reminders:
  name: Stop All Reminders
  description: Stop all active reminders
  fields: {}

stop_all:
  name: Stop All
  description: Stop all active alarms and reminders
  fields: {}